config/routes.rb
  match 'api/0.6/changeset/:id/expand_bbox' => 'changeset#expand_bbox', :via => :post, :id => /\d+/
  match 'api/0.6/changeset/:id' => 'changeset#read', :via => :get, :as => :changeset_read, :via => :get, :id => /\d+/
  match 'api/0.6/changeset/:id' => 'changeset#update', :via => :put, :id => /\d+/
  match 'api/0.6/changeset/:id/close' => 'changeset#close', :via => :put, :id => /\d+/
  match 'api/0.6/changesets' => 'changeset#query', :via => :get

  match 'api/0.6/node/create' => 'node#create', :via => :put
  match 'api/0.6/node/:id/ways' => 'way#ways_for_node', :via => :get, :id => /\d+/
  match 'api/0.6/node/:id/relations' => 'relation#relations_for_node', :via => :get, :id => /\d+/
  match 'api/0.6/node/:id/history' => 'old_node#history', :via => :get, :id => /\d+/
  match 'api/0.6/node/:id/:version/redact' => 'old_node#redact', :via => :post, :version => /\d+/, :id => /\d+/
  match 'api/0.6/node/:id/:version' => 'old_node#version', :via => :get, :id => /\d+/, :version => /\d+/
  match 'api/0.6/node/:id' => 'node#read', :via => :get, :id => /\d+/
  match 'api/0.6/node/:id' => 'node#update', :via => :put, :id => /\d+/
  match 'api/0.6/node/:id' => 'node#delete', :via => :delete, :id => /\d+/
  match 'api/0.6/nodes' => 'node#nodes', :via => :get

  match 'api/0.6/way/create' => 'way#create', :via => :put
  match 'api/0.6/way/:id/history' => 'old_way#history', :via => :get, :id => /\d+/
  match 'api/0.6/way/:id/full' => 'way#full', :via => :get, :id => /\d+/
  match 'api/0.6/way/:id/relations' => 'relation#relations_for_way', :via => :get, :id => /\d+/
  match 'api/0.6/way/:id/:version/redact' => 'old_way#redact', :via => :post, :version => /\d+/, :id => /\d+/
  match 'api/0.6/way/:id/:version' => 'old_way#version', :via => :get, :id => /\d+/, :version => /\d+/
  match 'api/0.6/way/:id' => 'way#read', :via => :get, :id => /\d+/
  match 'api/0.6/way/:id' => 'way#update', :via => :put, :id => /\d+/
  match 'api/0.6/way/:id' => 'way#delete', :via => :delete, :id => /\d+/
  match 'api/0.6/ways' => 'way#ways', :via => :get

  match 'api/0.6/relation/create' => 'relation#create', :via => :put
  match 'api/0.6/relation/:id/relations' => 'relation#relations_for_relation', :via => :get, :id => /\d+/
  match 'api/0.6/relation/:id/history' => 'old_relation#history', :via => :get, :id => /\d+/
  match 'api/0.6/relation/:id/full' => 'relation#full', :via => :get, :id => /\d+/
  match 'api/0.6/relation/:id/:version/redact' => 'old_relation#redact', :via => :post, :version => /\d+/, :id => /\d+/
  match 'api/0.6/relation/:id/:version' => 'old_relation#version', :via => :get, :id => /\d+/, :version => /\d+/
  match 'api/0.6/relation/:id' => 'relation#read', :via => :get, :id => /\d+/
  match 'api/0.6/relation/:id' => 'relation#update', :via => :put, :id => /\d+/
  match 'api/0.6/relation/:id' => 'relation#delete', :via => :delete, :id => /\d+/
  match 'api/0.6/relations' => 'relation#relations', :via => :get

  match 'api/0.6/map' => 'api#map', :via => :get

  match 'api/0.6/trackpoints' => 'api#trackpoints', :via => :get

  match 'api/0.6/changes' => 'api#changes', :via => :get

  match 'api/0.6/search' => 'search#search_all', :via => :get
  match 'api/0.6/ways/search' => 'search#search_ways', :via => :get
  match 'api/0.6/relations/search' => 'search#search_relations', :via => :get
  match 'api/0.6/nodes/search' => 'search#search_nodes', :via => :get

  match 'api/0.6/user/details' => 'user#api_details', :via => :get
  match 'api/0.6/user/preferences' => 'user_preference#read', :via => :get
  match 'api/0.6/user/preferences/:preference_key' => 'user_preference#read_one', :via => :get
  match 'api/0.6/user/preferences' => 'user_preference#update', :via => :put
  match 'api/0.6/user/preferences/:preference_key' => 'user_preference#update_one', :via => :put
  match 'api/0.6/user/preferences/:preference_key' => 'user_preference#delete_one', :via => :delete
  match 'api/0.6/user/gpx_files' => 'user#api_gpx_files', :via => :get

  match 'api/0.6/gpx/create' => 'trace#api_create', :via => :post
  match 'api/0.6/gpx/:id' => 'trace#api_read', :via => :get, :id => /\d+/
  match 'api/0.6/gpx/:id' => 'trace#api_update', :via => :put, :id => /\d+/
  match 'api/0.6/gpx/:id' => 'trace#api_delete', :via => :delete, :id => /\d+/
  match 'api/0.6/gpx/:id/details' => 'trace#api_read', :via => :get, :id => /\d+/
  match 'api/0.6/gpx/:id/data' => 'trace#api_data', :via => :get
  
  # AMF (ActionScript) API

  match 'api/0.6/amf/read' => 'amf#amf_read', :via => :post
  match 'api/0.6/amf/write' => 'amf#amf_write', :via => :post
  match 'api/0.6/swf/trackpoints' => 'swf#trackpoints', :via => :get

  # Data browsing
  match '/browse/start' => 'browse#start', :via => :get
  match '/browse/way/:id' => 'browse#way', :via => :get, :id => /\d+/
  match '/browse/way/:id/history' => 'browse#way_history', :via => :get, :id => /\d+/
  match '/browse/node/:id' => 'browse#node', :via => :get, :id => /\d+/
  match '/browse/node/:id/history' => 'browse#node_history', :via => :get, :id => /\d+/
  match '/browse/relation/:id' => 'browse#relation', :via => :get, :id => /\d+/
  match '/browse/relation/:id/history' => 'browse#relation_history', :via => :get, :id => /\d+/
  match '/browse/changeset/:id' => 'browse#changeset', :via => :get, :as => :changeset, :id => /\d+/
  match '/user/:display_name/edits' => 'changeset#list', :via => :get
  match '/user/:display_name/edits/feed' => 'changeset#feed', :via => :get, :format => :atom
  match '/browse/friends' => 'changeset#list', :via => :get, :friends => true, :as => "friend_changesets"
  match '/browse/nearby' => 'changeset#list', :via => :get, :nearby => true, :as => "nearby_changesets"
  match '/browse/changesets' => 'changeset#list', :via => :get
  match '/browse/changesets/feed' => 'changeset#feed', :via => :get, :format => :atom
  match '/browse' => 'changeset#list', :via => :get

  # web site
  root :to => 'site#index', :via => [:get, :post]
  match '/edit' => 'site#edit', :via => :get
  match '/copyright/:copyright_locale' => 'site#copyright', :via => :get
  match '/copyright' => 'site#copyright', :via => :get
  match '/history' => 'changeset#list', :via => :get
  match '/history/feed' => 'changeset#feed', :via => :get, :format => :atom
  match '/export' => 'site#export', :via => :get
  match '/login' => 'user#login', :via => [:get, :post]
  match '/logout' => 'user#logout', :via => [:get, :post]
  match '/offline' => 'site#offline', :via => :get
  match '/key' => 'site#key', :via => :post
  match '/user/new' => 'user#new', :via => :get
  match '/user/terms' => 'user#terms', :via => [:get, :post]
  match '/user/save' => 'user#save', :via => :post
  match '/user/:display_name/confirm/resend' => 'user#confirm_resend', :via => :get
  match '/user/:display_name/confirm' => 'user#confirm', :via => [:get, :post]
  match '/user/confirm' => 'user#confirm', :via => [:get, :post]
  match '/user/confirm-email' => 'user#confirm_email', :via => [:get, :post]
  match '/user/go_public' => 'user#go_public', :via => :post
  match '/user/reset-password' => 'user#reset_password', :via => [:get, :post]
  match '/user/forgot-password' => 'user#lost_password', :via => [:get, :post]
  match '/user/suspended' => 'user#suspended', :via => :get

  match '/index.html' => 'site#index', :via => :get
  match '/create-account.html' => 'user#new', :via => :get
  match '/forgot-password.html' => 'user#lost_password', :via => :get

  # permalink
  match '/go/:code' => 'site#permalink', :via => :get, :code => /[a-zA-Z0-9_@~]+[=-]*/

  # rich text preview
  match '/preview/:format' => 'site#preview', :as => :preview

  # traces
  match '/user/:display_name/traces/tag/:tag/page/:page' => 'trace#list', :via => :get
  match '/user/:display_name/traces/tag/:tag' => 'trace#list', :via => :get
  match '/user/:display_name/traces/page/:page' => 'trace#list', :via => :get
  match '/user/:display_name/traces' => 'trace#list', :via => :get
  match '/user/:display_name/traces/tag/:tag/rss' => 'trace#georss', :via => :get
  match '/user/:display_name/traces/rss' => 'trace#georss', :via => :get
  match '/user/:display_name/traces/:id' => 'trace#view', :via => :get
  match '/user/:display_name/traces/:id/picture' => 'trace#picture', :via => :get
  match '/user/:display_name/traces/:id/icon' => 'trace#icon', :via => :get
  match '/traces/tag/:tag/page/:page' => 'trace#list', :via => :get
  match '/traces/tag/:tag' => 'trace#list', :via => :get
  match '/traces/page/:page' => 'trace#list', :via => :get
  match '/traces' => 'trace#list', :via => :get
  match '/traces/tag/:tag/rss' => 'trace#georss', :via => :get
  match '/traces/rss' => 'trace#georss', :via => :get
  match '/traces/mine/tag/:tag/page/:page' => 'trace#mine', :via => :get
  match '/traces/mine/tag/:tag' => 'trace#mine', :via => :get
  match '/traces/mine/page/:page' => 'trace#mine', :via => :get
  match '/traces/mine' => 'trace#mine', :via => :get
  match '/trace/create' => 'trace#create', :via => [:get, :post]
  match '/trace/:id/data' => 'trace#data', :via => :get
  match '/trace/:id/edit' => 'trace#edit', :via => [:get, :post, :put]
  match '/trace/:id/delete' => 'trace#delete', :via => :post

  # diary pages
  match '/diary/new' => 'diary_entry#new', :via => [:get, :post]
  match '/diary/friends' => 'diary_entry#list', :friends => true, :via => :get, :as => "friend_diaries"
  match '/diary/nearby' => 'diary_entry#list', :nearby => true, :via => :get, :as => "nearby_diaries"
  match '/user/:display_name/diary/rss' => 'diary_entry#rss', :via => :get, :format => :rss
  match '/diary/:language/rss' => 'diary_entry#rss', :via => :get, :format => :rss
  match '/diary/rss' => 'diary_entry#rss', :via => :get, :format => :rss
  match '/user/:display_name/diary/comments/:page' => 'diary_entry#comments', :via => :get, :page => /\d+/
  match '/user/:display_name/diary/comments/' => 'diary_entry#comments', :via => :get
  match '/user/:display_name/diary' => 'diary_entry#list', :via => :get

app/helpers/user_helper.rb
module UserHelper
  def openid_logo
    image_tag "openid_small.png", :alt => t('user.login.openid_logo_alt'), :class => "openid_logo"
  end

  def openid_button(name, url)
    link_to(
      image_tag("#{name}.png", :alt => t("user.login.openid_providers.#{name}.alt")),
      "#",
      :class => "openid_button", "data-url" => url,
      :title => t("user.login.openid_providers.#{name}.title")
    )
  end
end

app/views/user/_map.html.erb
<%
if @user.home_lat.nil? or @user.home_lon.nil?
  lon = h(params['lon'] || '0') 
  lat = h(params['lat'] || '20') 
  zoom = h(params['zoom'] || '1') 
else 
  marker = true
  mlon = @user.home_lon 
  mlat = @user.home_lat
  lon =  @user.home_lon 
  lat =  @user.home_lat 
  zoom =  '12'
end
%>

<%= javascript_include_tag 'openlayers.js' %>
<%= javascript_include_tag 'map.js' %>

<script type="text/javascript">
  <!--
  var marker;

  OpenLayers.Lang.setCode("<%= I18n.locale.to_s %>");

  function init(){
    var centre = new OpenLayers.LonLat(<%= lon %>, <%= lat %>);
    <% if params[:scale].to_f > 0 then -%>
    var zoom = <%= scale_to_zoom params[:scale] %>;
    <% else -%>
    var zoom = <%= zoom %>;
    <% end -%>

    var map = createMap("map");

    setMapCenter(centre, zoom);

    <% if marker %>
    marker = addMarkerToMap(
      new OpenLayers.LonLat(<%= mlon %>, <%= mlat %>)
      <% if not setting_location %>
        , null, '<%=escape_javascript(render(:partial => "popup", :object => @user, :locals => { :type => "your location" })) %>'
      <% end %>
    );
    <% end %>
    
    <% if setting_location %>
    map.events.register("click", map, setHome);
    <% end %>
    
    <% if show_other_users %>
      <% friends = @user.friends.collect { |f| f.befriendee }.select { |f| !f.home_lat.nil? and !f.home_lon.nil? } %>
      <% nearest = @user.nearby - friends %>

      var near_icon = OpenLayers.Marker.defaultIcon();
      near_icon.url = OpenLayers.Util.getImageLocation("marker-green.png");
      <% nearest.each do |u| %>
        addMarkerToMap(new OpenLayers.LonLat(
          <%= u.home_lon %>, <%= u.home_lat %>), near_icon.clone(),
          '<%= escape_javascript(render(:partial => "popup", :object => u, :locals => { :type => "nearby mapper" })) %>'
        );
      <% end %>

      var friend_icon = OpenLayers.Marker.defaultIcon();
      friend_icon.url = OpenLayers.Util.getImageLocation("marker-blue.png");
      <% friends.each do |u| %>
        addMarkerToMap(new OpenLayers.LonLat(
          <%= u.home_lon %>, <%= u.home_lat %>), friend_icon.clone(),
          '<%= escape_javascript(render(:partial => "popup", :object => u, :locals => { :type => "friend" })) %>'
        );
      <% end %>
    <% end %>
  }        

  <% if setting_location %>
  function setHome( e ) { 
    closeMapPopup();

    if (document.getElementById('updatehome').checked) {
      var lonlat = getEventPosition(e);

      document.getElementById('homerow').className = '';
      document.getElementById('home_lat').value = lonlat.lat;
      document.getElementById('home_lon').value = lonlat.lon;

      if (marker) {
        removeMarkerFromMap(marker);
      }

      marker = addMarkerToMap(lonlat);
    }
  }
  <% end %>

  window.onload = init;
// -->
</script>

app/views/user/_popup.html.erb
<div class="user_popup">
  <%= user_thumbnail popup %>
  <p><%= t('user.popup.' + type) %></p>
  <p><%= link_to popup.display_name, :controller => "user", :action => "view", :display_name => popup.display_name %></p>
</div>

app/views/user/_terms.html.erb
<p id="first">
  <%= raw @text['intro'] %>
  <%= raw @text['next_with_decline'] %>
</p>
<h3><%= raw @text['introduction'] %></h3>
<ol>
  <li>
    <p><%= raw @text['section_1'] %></p>
    <% unless @text['section_1a'].nil? %>
    <ol style="list-style-type: lower-alpha">
      <li><%= raw @text['section_1a'] %></li>
      <li><%= raw @text['section_1b'] %></li>
    </ol>
    <% end %>
  </li>
</ol>
<h3><%= raw @text['rights_granted'] %></h3>
<ol start="2">
  <li>
    <p><%= raw @text['section_2'] %></p>
  </li>
  <li>
    <p><%= raw @text['section_3'] %></p>
    <p><%= raw @text['active_defn_1'] %></p>
    <p><%= raw @text['active_defn_2'] %></p>
    </ul>
  </li>
  <li>
    <p><%= raw @text['section_4'] %></p>
  </li>
  <li>
    <p><%= raw @text['section_5'] %></p>
  </li>
</ol>
<h3><%= raw @text['limitation_of_liability'] %></h3>
<ol start="6">
  <li><p><%= raw @text['section_6'] %></p></li>
  <li><p><%= raw @text['section_7'] %></p></li>
</ol>
<h3><%= raw @text['miscellaneous'] %></h3>
<ol start="8">
  <li>
    <p id="last"><%= raw @text['section_8'] %></p>
  </li>
</ol>

app/views/user/blocked.html.erb
<h1><%= t 'user.new.heading' %></h1>

<p><%= t 'user.new.no_auto_account_create' %></p>

<p><%= raw t 'user.new.contact_webmaster' %></p>

app/views/user/confirm.html.erb
<script>
$("#content").hide();
</script>

<h1><%= t 'user.confirm.heading' %></h1>

<p><%= t 'user.confirm.press confirm button' %></p>

<%= form_tag({}, { :id => "confirm" }) do %>
  <input type="display_name" name="confirm_string" value="<%= params[:display_name] %>">
  <input type="hidden" name="confirm_string" value="<%= params[:confirm_string] %>">
  <input type="submit" name="confirm_action" value="<%= t 'user.confirm.button' %>">
<% end %>

<script>
$("#confirm").submit();
</script>

app/views/user/list.html.erb
<% @title = t('user.list.title') %>

<h1><%= t('user.list.heading') %></h1>

<% unless @users.empty? %>
  <%= form_tag do %>
    <%= hidden_field_tag :status, params[:status] if params[:status] %>
    <%= hidden_field_tag :ip, params[:ip] if params[:ip] %>
    <%= hidden_field_tag :page, params[:page] if params[:page] %>
    <table id="user_list">
      <tr>
        <td colspan="2">
          <%= t 'user.list.showing',
              :page => @user_pages.current_page.number,
              :first_item => @user_pages.current_page.first_item,
              :last_item => @user_pages.current_page.last_item,
              :items => @user_pages.item_count,
              :count => @user_pages.current_page.last_item - @user_pages.current_page.first_item + 1
          %>
          <% if @user_pages.page_count > 1 %>
          | <%= raw pagination_links_each(@user_pages, {}) { |n| link_to n, params.merge(:page => n) } %>
          <% end %>
        </td>
        <td>
          <%= check_box_tag "user_all", "1", false %>
        </td>
      </tr>
      <%= render :partial => 'user', :collection => @users %>
    </table>

    <div id="user_list_actions">
      <%= submit_tag t('user.list.confirm'), :name => "confirm" %>
      <%= submit_tag t('user.list.hide'), :name => "hide" %>
    </div>

    <script type="text/javascript">
     $("#user_all").change(function () {
       $("#user_list input[type=checkbox]").prop("checked", $("#user_all").prop("checked"));
     });
    </script>
  <% end %>
<% else %>
  <p><%= t "user.list.empty" %></p>
<% end %>

app/views/user/logout.html.erb
<h1><%= t 'user.logout.heading' %></h1>
<%= form_tag :action => "logout" do %>
  <%= hidden_field_tag("referer", h(params[:referer])) %>
  <%= hidden_field_tag("session", request.session_options[:id]) %>
  <%= submit_tag t('user.logout.logout_button') %>
<% end %>

app/views/user/lost_password.html.erb
<h1><%= t 'user.lost_password.heading' %></h1>

<p><%= t 'user.lost_password.help_text' %></p>

<%= form_tag :action => 'lost_password' do %>
<table>
  <tr>
    <td class="fieldName"><%= t 'user.lost_password.email address' %></td>
    <td><%= text_field('user', 'email', {:size => 50, :maxlength => 255, :tabindex => 1} ) %></td>
  </tr>
  <tr>
    <td></td>
    <td class="submitButton"><input type="submit" value="<%= t'user.lost_password.new password button' %>" tabindex="2"></td>
  </tr>
</table>
<% end %>

app/views/user/reset_password.html.erb
<h1><%= t 'user.reset_password.heading', :user => @user.display_name %></h1>

<%= error_messages_for :user %>

<%= form_tag do %>
<%= hidden_field_tag(:token, params[:token]) %>
<table id="loginForm">
  <tr><td class="fieldName"><%= t 'user.reset_password.password' %></td><td><%= password_field(:user, :pass_crypt, {:value => '', :size => 30, :maxlength => 255, :tabindex => 4}) %></td></tr>
  <tr><td class="fieldName"><%= t 'user.reset_password.confirm password' %></td><td><%= password_field(:user, :pass_crypt_confirmation, {:value => '', :size => 30, :maxlength => 255, :tabindex => 5}) %></td></tr>
  
  <tr><td colspan=2>&nbsp;<!--vertical spacer--></td></tr>
  <tr><td></td><td class="submitButton"><input type="submit" value="<%= t'user.reset_password.reset' %>" tabindex="6"></td></tr>
</table>
<% end %>

app/views/user/view.html.erb
<%= user_image @this_user %>

<h2><%= @this_user.display_name %><%= role_icons(@this_user) %></h2>

<div id="userinformation">
  <% if @user and @this_user.id == @user.id %>
    <!-- Displaying user's own profile page -->
    <%= link_to t('user.view.my diary'), :controller => 'diary_entry', :action => 'list', :display_name => @user.display_name %>
    |
    <%= link_to t('user.view.new diary entry'), :controller => 'diary_entry', :action => 'new' %>
    |
    <%= link_to t('user.view.my comments' ), :controller => 'diary_entry', :action => 'comments', :display_name => @this_user.display_name %>
    |
    <%= link_to t('user.view.my edits'), :controller => 'changeset', :action => 'list', :display_name => @user.display_name %>
    |
    <%= link_to t('user.view.my traces'), :controller => 'trace', :action=>'mine' %>
    |
    <%= link_to t('user.view.my settings'), :controller => 'user', :action => 'account', :display_name => @user.display_name %>
    |
    <%= link_to t('user.view.oauth settings'), :controller => 'oauth_clients', :action => 'index' %>
    |
    <%= link_to t('user.view.blocks on me'), :controller => 'user_blocks', :action => 'blocks_on', :display_name => @user.display_name %>
    <% if @user and @user.moderator? %>
      | <%= link_to t('user.view.blocks by me'), :controller => 'user_blocks', :action => 'blocks_by', :display_name => @user.display_name %>
    <% end %>
  <% else %>
    <!-- Displaying another user's profile page -->
    <%= link_to t('user.view.send message'), :controller => 'message', :action => 'new', :display_name => @this_user.display_name %>
    |
    <%= link_to t('user.view.diary'), :controller => 'diary_entry', :action => 'list', :display_name => @this_user.display_name %>
    |
    <%= link_to t('user.view.comments'), :controller => 'diary_entry', :action => 'comments', :display_name => @this_user.display_name %>
    |
    <%= link_to t('user.view.edits'), :controller => 'changeset', :action => 'list', :display_name => @this_user.display_name %>
    |
    <%= link_to t('user.view.traces'), :controller => 'trace', :action => 'list', :display_name => @this_user.display_name %>
    |
    <% if @user and @user.is_friends_with?(@this_user) %>
      <%= link_to t('user.view.remove as friend'), :controller => 'user', :action => 'remove_friend', :display_name => @this_user.display_name %>
    <% else %>
      <%= link_to t('user.view.add as friend'), :controller => 'user', :action => 'make_friend', :display_name => @this_user.display_name %>
    <% end %>
    |
    <%= link_to t('user.view.block_history'), :controller => 'user_blocks', :action => 'blocks_on', :display_name => @this_user.display_name %>
    <% if @this_user.moderator? %>
      | <%= link_to t('user.view.moderator_history'), :controller => 'user_blocks', :action => 'blocks_by', :display_name => @this_user.display_name %>
    <% end %>
    <% if @user and @user.moderator? %>
      | <%= link_to t('user.view.create_block'), :controller => 'user_blocks', :action => 'new', :display_name => @this_user.display_name %>
    <% end %>
  <% end %>
  <% if @user and @user.administrator? %>
    <br/>
    <% if ["active", "confirmed"].include? @this_user.status %>
      <%= link_to t('user.view.deactivate_user'), {:controller => 'user', :action => 'set_status', :status => 'pending', :display_name => @this_user.display_name}, {:confirm => t('user.view.confirm')} %> |
    <% elsif ["pending"].include? @this_user.status %>
      <%= link_to t('user.view.activate_user'), {:controller => 'user', :action => 'set_status', :status => 'active', :display_name => @this_user.display_name}, {:confirm => t('user.view.confirm')} %> |
    <% end %>
    <% if ["active", "suspended"].include? @this_user.status %>
      <%= link_to t('user.view.confirm_user'), {:controller => 'user', :action => 'set_status', :status => 'confirmed', :display_name => @this_user.display_name}, {:confirm => t('user.view.confirm')} %> |
    <% end %>
    <% if ["pending", "active", "confirmed", "suspended"].include? @this_user.status %>
      <%= link_to t('user.view.hide_user'), {:controller => 'user', :action => 'set_status', :status => 'deleted', :display_name => @this_user.display_name}, {:confirm => t('user.view.confirm')} %> |
    <% else %>
      <%= link_to t('user.view.unhide_user'), {:controller => 'user', :action => 'set_status', :status => 'active', :display_name => @this_user.display_name}, {:confirm => t('user.view.confirm')} %> |
    <% end %>
    <%= link_to t('user.view.delete_user'), {:controller => 'user', :action => 'delete', :display_name => @this_user.display_name}, {:confirm => t('user.view.confirm')} %>
  <% end %>
</div>

<p><b><%= t 'user.view.mapper since' %></b> <%= l @this_user.creation_time, :format => :friendly %> <%= t 'user.view.ago', :time_in_words_ago => time_ago_in_words(@this_user.creation_time) %></p>

<p><b><%= t 'user.view.ct status' %></b>
<% if not @this_user.terms_agreed.nil? -%>
<%= t 'user.view.ct accepted', :ago =>time_ago_in_words(@this_user.terms_agreed)  %> 
<% elsif not @this_user.terms_seen? -%>
<%= t 'user.view.ct undecided' %>
<% else -%>
<%= t 'user.view.ct declined' %>
<% end -%>
</p>

<% if @user and @user.administrator? -%>
  <p><b><%= t 'user.view.email address' %></b> <%= @this_user.email %></p>  
  <% unless @this_user.creation_ip.nil? -%>
  <p><b><%= t 'user.view.created from' %></b> <%= @this_user.creation_ip %></p>
  <% end -%>
  <p><b><%= t 'user.view.status' %></b> <%= @this_user.status.capitalize %></p>
  <p><b><%= t 'user.view.spam score' %></b> <%= @this_user.spam_score %></p>
<% end -%>

<h3><%= t 'user.view.description' %></h3>

<div id="description"><%= @this_user.description.to_html %></div>

<% if @user and @this_user.id == @user.id %>
  <div id="map" class="user_map">
    <% if @this_user.home_lat.nil? or @this_user.home_lon.nil? %>
      <p id="no_home_location"><%= raw(t 'user.view.if set location', :settings_link => (link_to t('user.view.settings_link_text'), :controller => 'user', :action => 'account', :display_name => @user.display_name)) %></p>
    <% else %>
      <%= render :partial => 'map', :locals => { :setting_location => false, :show_other_users => true } %>
    <% end %>
  </div>

  <% friends = @this_user.friends.collect { |f| f.befriendee } %>
  <% nearby = @this_user.nearby - friends %>

  <h3 style="margin-top: 0"><%= t 'user.view.your friends' %></h3>

  <% if friends.empty? %>
    <%= t 'user.view.no friends' %>
  <% else %>
    <%= link_to t('user.view.friends_changesets'), friend_changesets_path %><br/>
    <%= link_to t('user.view.friends_diaries'), friend_diaries_path %><br/><br/>
    <table id="friends">
      <%= render :partial => "contact", :collection => friends %>
    </table>
  <% end %>

  <h3><%= t 'user.view.nearby users' %></h3>

  <% if nearby.empty? %>
    <%= t 'user.view.no nearby users' %>
  <% else %>
    <%= link_to t('user.view.nearby_changesets'), nearby_changesets_path %><br/>
    <%= link_to t('user.view.nearby_diaries'), nearby_diaries_path %><br/><br/>
    <table id="nearbyusers">
      <%= render :partial => "contact", :collection => nearby %>
    </table>
  <% end %>
<% end %>